import chromadb
from llama_index.graph_stores.neo4j import Neo4jPropertyGraphStore
from llama_index.vector_stores.chroma import ChromaVectorStore
from backend.core.config import settings

from typing import List
from llama_index.core.graph_stores.types import LabelledNode, EntityNode, ChunkNode

class CustomNeo4jPropertyGraphStore(Neo4jPropertyGraphStore):
    """
    Subclass of Neo4jPropertyGraphStore that overrides upsert_nodes to fix
    Cypher subquery syntax compatibility with Neo4j 5.x.
    """
    @property
    def supports_vector_queries(self) -> bool:
        return False

    def upsert_nodes(self, nodes: List[LabelledNode]) -> None:
        entity_dicts: List[dict] = []
        chunk_dicts: List[dict] = []

        # Sort by type
        for item in nodes:
            if isinstance(item, EntityNode):
                entity_dicts.append({**item.dict(), "id": item.id})
            elif isinstance(item, ChunkNode):
                chunk_dicts.append({**item.dict(), "id": item.id})

        if chunk_dicts:
            for index in range(0, len(chunk_dicts), 512):
                chunked_params = chunk_dicts[index : index + 512]
                self.structured_query(
                    f"""
                    UNWIND $data AS row
                    MERGE (c:__Node__ {{id: row.id}})
                    SET c.text = row.text, c:Chunk
                    WITH c, row
                    SET c += row.properties
                    WITH c, row.embedding AS embedding
                    WHERE embedding IS NOT NULL
                    CALL db.create.setNodeVectorProperty(c, 'embedding', embedding)
                    RETURN count(*)
                    """,
                    param_map={"data": chunked_params},
                )

        if entity_dicts:
            for index in range(0, len(entity_dicts), 512):
                chunked_params = entity_dicts[index : index + 512]
                self.structured_query(
                    f"""
                    UNWIND $data AS row
                    MERGE (e:__Node__ {{id: row.id}})
                    SET e += apoc.map.clean(row.properties, [], [])
                    SET e.name = row.name, e:`__Entity__`
                    WITH e, row
                    CALL apoc.create.addLabels(e, [row.label])
                    YIELD node
                    WITH e, row
                    CALL {{
                        WITH e, row
                        WITH e, row WHERE row.embedding IS NOT NULL
                        CALL db.create.setNodeVectorProperty(e, 'embedding', row.embedding)
                        RETURN count(*) AS count
                    }}
                    WITH e, row WHERE row.properties.triplet_source_id IS NOT NULL
                    MERGE (c:__Node__ {{id: row.properties.triplet_source_id}})
                    MERGE (e)<-[:MENTIONS]-(c)
                    """,
                    param_map={"data": chunked_params},
                )

def get_neo4j_graph_store() -> CustomNeo4jPropertyGraphStore:
    """
    Get the Neo4j graph store instance.
    """
    return CustomNeo4jPropertyGraphStore(
        username=settings.NEO4J_USER,
        password=settings.NEO4J_PASSWORD,
        url=settings.NEO4J_URI,
        database="neo4j"
    )

def get_chroma_vector_store() -> ChromaVectorStore:
    """
    Get the ChromaDB vector store instance, pointing to the dedicated `kg_nodes` collection.
    
    CRITICAL: This ensures that all node embeddings generated by PropertyGraphIndex
    are stored separately inside ChromaDB, and NOT inside Neo4j's native vector index.
    """
    client = chromadb.HttpClient(
        host=settings.CHROMA_HOST,
        port=settings.CHROMA_PORT
    )
    collection = client.get_or_create_collection("kg_nodes")
    return ChromaVectorStore(chroma_collection=collection)

def get_llm(model: str = "gpt-4o-mini", temperature: float = 0.0):
    """
    Get a configured LlamaIndex LLM instance, supporting OpenRouter fallback.
    """
    from llama_index.llms.openai import OpenAI
    openai_key = settings.OPENAI_API_KEY
    kw = {
        "model": model,
        "temperature": temperature,
        "api_key": openai_key
    }
    if openai_key and (openai_key.startswith("sk-or-") or "openrouter" in openai_key):
        kw["api_base"] = "https://openrouter.ai/api/v1"
    return OpenAI(**kw)
