import chromadb
from llama_index.graph_stores.neo4j import Neo4jPropertyGraphStore
from llama_index.vector_stores.chroma import ChromaVectorStore
from backend.core.config import settings

def get_neo4j_graph_store() -> Neo4jPropertyGraphStore:
    """
    Get the Neo4j graph store instance.
    """
    return Neo4jPropertyGraphStore(
        username=settings.NEO4J_USER,
        password=settings.NEO4J_PASSWORD,
        url=settings.NEO4J_URI,
        database="neo4j"
    )

def get_chroma_vector_store() -> ChromaVectorStore:
    """
    Get the ChromaDB vector store instance, pointing to the dedicated `kg_nodes` collection.
    
    CRITICAL: This ensures that all node embeddings generated by PropertyGraphIndex
    are stored separately inside ChromaDB, and NOT inside Neo4j's native vector index.
    """
    client = chromadb.HttpClient(
        host=settings.CHROMA_HOST,
        port=settings.CHROMA_PORT
    )
    collection = client.get_or_create_collection("kg_nodes")
    return ChromaVectorStore(chroma_collection=collection)
